"""
Django settings for paylab project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-18m6^u40(w()0ii-rh56%2)=*=91)3q%kt1sw#@ip$8=*!=kj5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'user',
    'rest_framework.authtoken',
    "wallet",
    "billPayment"
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'paylab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'paylab.wsgi.application'

# rest framework specification

REST_FRAMEWORK = {
    "NON_FIELD_ERRORS_KEY":"errors",
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated'
    ),

}

#custom user model
AUTH_USER_MODEL ="user.User"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Logging
logging.basicConfig(
    filename='partytime.log',
    filemode='a',
    level=logging.DEBUG,
    format='[{asctime}] {levelname} {module} {thread:d} - {message}',
    datefmt='%d-%m-%Y %H:%M:%S',
    style='{',
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {module} {thread:d} - {message}',
            'style': '{',
            'datefmt': '%d-%m-%Y %H:%M:%S'
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'partytime.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.server': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.response': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
image_url = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.pinimg.com%2Foriginals%2F82%2Fc6%2F5b%2F82c65b9bb0a75026fc4c82a438b4cc9b.jpg&tbnid=uuFWcTg4EEDF6M&vet=12ahUKEwj30ZvTq5CFAxX-UqQEHTqTBT4QMygGegQIARB9..i&imgrefurl=https%3A%2F%2Fwww.pinterest.com%2Fpin%2Fcreative-logo-designs--759560293395419580%2F&docid=UbhDGLPiGJG40M&w=1079&h=1028&q=logo&ved=2ahUKEwj30ZvTq5CFAxX-UqQEHTqTBT4QMygGegQIARB9"

BANK_LIST = [
    {
        "name": "Sterling Bank",
        "id": "000001",
        "image": image_url
    },
    {
        "name": "Keystone Bank",
        "id": "000002",
        "image": image_url
    },
    {
        "name": "FCMB",
        "id": "000003",
        "image": image_url
    },
    {
        "name": "United Bank for Africa",
        "id": "000004",
        "image": image_url
    },
    {
        "name": "Diamond Bank",
        "id": "000005",
        "image": image_url
    },
    {
        "name": "JAIZ Bank",
        "id": "000006",
        "image": image_url
    },
    {
        "name": "Fidelity Bank",
        "id": "000007",
        "image": image_url
    },
    {
        "name": "Polaris Bank",
        "id": "000008",
        "image": image_url
    },
    {
        "name": "Citi Bank",
        "id": "000009",
        "image": image_url
    },
    {
        "name": "Ecobank Bank",
        "id": "000010",
        "image": image_url
    },
    {
        "name": "Unity Bank",
        "id": "000011",
        "image": image_url
    },
    {
        "name": "StanbicIBTC Bank",
        "id": "000012",
        "image": image_url
    },
    {
        "name": "GTBank Plc",
        "id": "000013",
        "image": image_url
    },
    {
        "name": "Access Bank",
        "id": "000014",
        "image": image_url
    },
    {
        "name": "Zenith Bank Plc",
        "id": "000015",
        "image": image_url
    },
    {
        "name": "First Bank of Nigeria",
        "id": "000016",
        "image": image_url
    },
    {
        "name": "Wema Bank",
        "id": "000017",
        "image": image_url
    },
    {
        "name": "Union Bank",
        "id": "000018",
        "image": image_url
    },
    {
        "name": "Enterprise Bank",
        "id": "000019",
        "image": image_url
    },
    {
        "name": "Heritage",
        "id": "000020",
        "image": image_url
    },
    {
        "name": "StandardChartered",
        "id": "000021",
        "image": image_url
    },
    {
        "name": "Suntrust Bank",
        "id": "000022",
        "image": image_url
    },
    {
        "name": "Providus Bank",
        "id": "000023",
        "image": image_url
    },
    {
        "name": "Rand Merchant Bank",
        "id": "000024",
        "image": image_url
    },
    {
        "name": "Titan Trust Bank",
        "id": "000025",
        "image": image_url
    },
    {
        "name": "Taj Bank",
        "id": "000026",
        "image": image_url
    },
    {
        "name": "Globus Bank",
        "id": "000027",
        "image": image_url
    },
    {
        "name": "Central Bank of Nigeria",
        "id": "000028",
        "image": image_url
    },
    {
        "name": "Lotus Bank",
        "id": "000029",
        "image": image_url
    },
    {
        "name": "Premium Trust Bank",
        "id": "000031",
        "image": image_url
    },
    {
        "name": "eNaira",
        "id": "000033",
        "image": image_url
    }
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=20),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=60),
    "AUTH_HEADER_TYPES": ("Bearer","Token"),
    'UPDATE_LAST_LOGIN': True,
    "SIGNING_KEY": SECRET_KEY,

}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT='/usr/paylab/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/usr/paylab/media/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_FROM_USER = 'supports@paylab.finance'
EMAIL_HOST = 'mail.paylab.finance'
EMAIL_HOST_USER =  'supports@paylab.finance'
EMAIL_HOST_PASSWORD ='hub360@123'  
EMAIL_PORT = 465
EMAIL_USE_SSL = True
# EMAIL_USE_TLS = True
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
