# Generated by Django 4.2.2 on 2023-06-29 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=20)),
                ('unique_id', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='DataBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataplan', models.CharField(max_length=60)),
                ('day', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
                ('unique_id', models.CharField(max_length=6)),
                ('networkType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billPayment.networktype')),
            ],
        ),
    ]
