# Generated by Django 4.2.2 on 2023-07-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billPayment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(max_length=10)),
                ('disco', models.CharField(max_length=60)),
                ('unique_id', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('cableplan', models.CharField(max_length=60)),
                ('planname', models.CharField(max_length=60)),
                ('amount', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('unique_id', models.CharField(max_length=6)),
            ],
        ),
    ]
