# Generated by Django 4.2.2 on 2023-07-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billPayment', '0002_bills_cable_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='meter_type',
            field=models.CharField(max_length=30),
        ),
    ]
