# Generated by Django 4.2.2 on 2023-08-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_nameofsaving_vault_transaction_settlementid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='vault',
            name='fundedAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='funded amount'),
        ),
        migrations.AlterField(
            model_name='vault',
            name='withdrawAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='withdraw amount'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
