# Generated by Django 4.2.2 on 2023-08-17 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_vault_balance_alter_vault_fundedamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField()),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vault',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='fundedAmount',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='withdrawAmount',
        ),
        migrations.AddField(
            model_name='vault',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='payback_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='saved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='vault_type',
            field=models.CharField(blank=True, choices=[('safe', 'Safe Lock'), ('target', 'Target Lock')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vault',
            name='percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vault',
            name='duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.duration'),
        ),
    ]
