# Generated by Django 4.2.2 on 2024-03-22 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0006_vault_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
